---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "fluxv2.labels" . | nindent 4 }}
    control-plane: controller
  name: helm-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.helm.replicaCount }}
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      annotations:
      {{- if .Values.prometheus.enabled }}
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      {{- end }}
      labels:
        app: helm-controller
    spec:
      containers:
      - args:
        - --events-addr=http://notification-controller/
        - --watch-all-namespaces=true
        - --log-level=info
        - --log-encoding=json
        - --enable-leader-election
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.helm.image.repository }}:{{ .Values.helm.image.tag }}
        imagePullPolicy: {{ .Values.helm.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9440
          name: healthz
          protocol: TCP
        - containerPort: 8080
          name: http-prom
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        resources:
        {{- if .Values.helm.resources }}
          {{- toYaml .Values.helm.resources | nindent 12 }}
        {{- else }}
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: temp
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: helm-controller
      terminationGracePeriodSeconds: 600
      volumes:
      - emptyDir: {}
        name: temp
