{{- if .Values.helm.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluxv2.labels" . | nindent 4 }}
  {{- with .Values.helm.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
