---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "fluxv2.labels" . | nindent 4 }}
    control-plane: controller
  name: notification-controller
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: notification-controller
  type: ClusterIP
