apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "fluxv2.labels" . | nindent 4 }}
    control-plane: controller
  name: notification-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.notification_controller.replicaCount }}
  selector:
    matchLabels:
      app: notification-controller
  template:
    metadata:
      annotations:
      {{- if .Values.prometheus.enabled }}
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      {{- end }}
      labels:
        app: notification-controller
    spec:
      containers:
      - args:
        - --watch-all-namespaces=true
        - --log-level=info
        - --log-encoding=json
        - --enable-leader-election
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.notification_controller.image.repository }}:{{ .Values.notification_controller.image.tag }}
        imagePullPolicy: {{ .Values.notification_controller.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9440
          name: healthz
          protocol: TCP
        - containerPort: 9090
          name: http
        - containerPort: 9292
          name: http-webhook
        - containerPort: 8080
          name: http-prom
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        resources:
        {{- if .Values.notification_controller.resources }}
          {{- toYaml .Values.notification_controller.resources | nindent 12 }}
        {{- else }}
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: temp
      nodeSelector:
      {{- if .Values.notification_controller.nodeSelector }}
        {{- toYaml .Values.notification_controller.nodeSelector | nindent 12 }}
      {{- end }}
        kubernetes.io/os: linux
      serviceAccountName: notification-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: temp